import { StyleSheet } from "react-native";

export default StyleSheet.create({
  container: {
    flex: 1,
    alignItems: "center",
  },
  input: {
    height: 48,
    borderRadius: 5,
    overflow: "hidden",
    backgroundColor: "white",
    marginTop: 10,
    marginBottom: 10,
    marginLeft: 30,
    marginRight: 30,
    paddingLeft: 100,
  },
  button: {
    backgroundColor: "#788eec",
    marginLeft: 100,
    marginRight: 100,
    marginTop: 20,
    height: 48,
    borderRadius: 5,
    alignItems: "center",
    justifyContent: "center",
    paddingLeft: 50,
    paddingRight: 50,
  },
  button2: {
    backgroundColor: "#788eec",
    marginLeft: 20,
    marginRight: 20,
    marginTop: -10,
    height: 48,
    borderRadius: 5,
    alignItems: "center",
    justifyContent: "center",
    paddingLeft: 20,
    paddingRight: 20,
  },
  buttonTitle: {
    color: "white",
    fontSize: 16,
    fontWeight: "bold",
    alignItems: "center",
  },
  DBtext: {
    color: "black",
    fontSize: 18,
    fontWeight: "bold",
    alignItems: "center",
  },
});
